[package]
name = "TheProfitTaker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
cudnn = "1.3.1"
curl = "0.4.44"
dotenv = "0.15.0"
fil-rustacuda = "0.1.4"
libc = "0.2.147"
serde = "1.0.188"
serde_json = "1.0.105"
ta-lib-sys = "0.1.2"

polars = { version = "0.32.1", features = ["lazy", "json", "ndarray"] }