[package]
name = "TheProfitTaker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0.83"

[dependencies]
anyhow = "1.0.75"
curl = "0.4.44"
dotenv = "0.15.0"
lazy_static = "1.4.0"
libc = "0.2.147"
rand = "0.8.5"
rcublas = "0.6.0"
rcudnn = "1.8.0"
serde = "1.0.188"
serde_json = "1.0.105"
ta-lib-sys = "0.1.2"

cust = { version = "0.3.2", features = ["bytemuck"] }
polars = { version = "0.32.1", features = ["lazy", "json", "ndarray"] }
