[package]
name = "TheProfitTaker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cuda-runtime-sys = "0.3.0-alpha.1"
curl = "0.4.44"
dotenv = "0.15.0"
json = "0.12.4"
polars = "0.32.1"
ta = "0.5.0"

