[package]
name = "Milkshake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
curl = "0.4.44"
dotenv = "0.15.0"
lazy_static = "1.4.0"
libc = "0.2.147"
rand = "0.8.5"
serde = "1.0.188"
serde_json = "1.0.105"
tch = "0.13.0"

ta-lib-sys = { version = "0.1.2", features = ["use_system_lib"]}
polars = { version = "0.33.2", features = ["cross_join", "json", "lazy", "ndarray", "strings"] }
mujoco-rust = "0.0.6"
