name: Update Cargo Dependencies

on:
  schedule:
    - cron: '30 2 15 * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Install Cargo Updater
        run: |
          cargo install -f cargo-upgrades
          cargo install -f cargo-edit

      - name: Update dependencies
        run: |
          cargo upgrade --incompatible
          cargo update

      - name: Push updates to origin
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          
          git commit -m "Auto Update Dependencies"
          git push

  call_build:
    needs: update
    uses: ./.github/workflows/rust.yml
