name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install PyTorch
      run: pip3 install torch --index-url https://download.pytorch.org/whl/cu118

    - name: Install MuJoCo
      run: |
        MUJOCO_URL_LATEST=$(curl -s https://api.github.com/repos/google-deepmind/mujoco/releases/latest | grep browser_download_url | grep linux.x86_64.tar.gz | cut -d '"' -f 4 | sed '1p;d')
        curl -L $MUJOCO_URL_LATEST > mujoco.tar.gz && tar -xvzf mujoco.tar.gz
        sudo cp -r $(ls | grep mujoco | sed '1p;d') ~/.local/mujoco/
        sudo cp -a ~/.local/mujoco/lib/. /usr/lib/

    - name: Install Depends
      run: |
        sudo apt-get update
        sudo apt-get install xorg-dev libglu1-mesa-dev

    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
