name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Grab Latest Pytorch Info
      run: curl -s https://api.github.com/repos/pytorch/pytorch/releases/latest >> pytorchinfo.txt
    
    - uses: actions/cache@v3
      with:
        path: pytorch-static
        key: ${{ runner.os }}-pytorch-${{ hashFiles('pytorchinfo.txt') }}
    - name: Install PyTorch
      run: |
        PYTORCH_TAG_LATEST=$(curl -s https://api.github.com/repos/pytorch/pytorch/releases/latest | grep tag_name | cut -d '"' -f 4 | sed '1p;d')
        git clone -b $PYTORCH_TAG_LATEST --recurse-submodule https://github.com/pytorch/pytorch.git pytorch-static --depth 1

        cd pytorch-static
        BUILD_SHARED_LIBS=OFF python setup.py build

        ls
        
        sudo pip3 install torch --index-url https://download.pytorch.org/whl/cu118
        echo "LIBTORCH_USE_PYTORCH=1" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/python3.10/dist-packages/torch/lib/" >> $GITHUB_ENV

    - name: Install MuJoCo
      run: |
        MUJOCO_URL_LATEST=$(curl -s https://api.github.com/repos/google-deepmind/mujoco/releases/latest | grep browser_download_url | grep linux.x86_64.tar.gz | cut -d '"' -f 4 | sed '1p;d')
        curl -L $MUJOCO_URL_LATEST > mujoco.tar.gz && tar -xvzf mujoco.tar.gz
        sudo cp -r $(ls | grep mujoco | sed '1p;d') ~/.local/mujoco/
        sudo cp -a ~/.local/mujoco/lib/. /usr/lib/

    - name: Install GLFW Depends
      run: |
        sudo apt-get update
        sudo apt-get install xorg-dev libglu1-mesa-dev
      
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
