name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Torch
      run: |
        curl -L https://download.pytorch.org/libtorch/nightly/cu118/libtorch-shared-with-deps-latest.zip > libtorch-shared-with-deps-latest.zip && unzip libtorch-shared-with-deps-latest.zip
        sudo cp -a libtorch/bin/. /usr/local/bin/
        sudo cp -a libtorch/include/. /usr/share/include/
        sudo cp -a libtorch/lib/. /usr/lib/lib/
        sudo cp -a libtorch/share/. /usr/share/share/
        
    - name: Install TA-Lib
      run: |
        curl -L  http://downloads.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz > ta-lib-0.4.0-src.tar.gz && tar -xzvf ta-lib-0.4.0-src.tar.gz
        cd ta-lib && ./configure --prefix=/usr
        cd ta-lib && make
        cd ta-lib && sudo make install
        
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
