name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  pytorch:

    runs-on: ubuntu-latest

    steps:
    - name: Install Cuda
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
        sudo dpkg -i cuda-keyring_1.1-1_all.deb
        sudo apt-get update
        sudo apt-get -y install cuda-11-8 libcudnn8 libcudnn8-dev build-essential ninja-build
        echo "/usr/local/cuda/bin" >> $GITHUB_PATH
    
    - name: Grab Latest Pytorch Info
      run: curl -s https://api.github.com/repos/pytorch/pytorch/releases/latest >> pytorchinfo.txt
    
    - uses: actions/cache@master
      with:
        path: pytorch-static
        key: ${{ runner.os }}-pytorch-${{ hashFiles('pytorchinfo.txt') }}
        
    - name: Install PyTorch
      run: |
        PYTORCH_TAG_LATEST=$(cat pytorchinfo.txt | grep tag_name | cut -d '"' -f 4 | sed '1p;d')
        git clone -b $PYTORCH_TAG_LATEST --recurse-submodule https://github.com/pytorch/pytorch.git pytorch-static --depth 1

        echo "_GLIBCXX_USE_CXX11_ABI=1" >> $GITHUB_ENV
        echo "BUILD_SHARED_LIBS=OFF" >> $GITHUB_ENV
        
        cd pytorch-static && python setup.py build --cmake-only
        cd build && cmake . && ninja
        
    - uses: actions/upload-artifact@master
      with:
        name: pytorch-static
        path: pytorch-static
          
  build:

    runs-on: ubuntu-latest
    needs: pytorch

    steps:
    - name: Install Depends
      run: |
        sudo apt-get -y install xorg-dev libglu1-mesa-dev

    - uses: actions/download-artifact@master
      with:
        name: pytorch-static
        path: pytorch-static
    
    - name: Install MuJoCo
      run: |
        MUJOCO_URL_LATEST=$(curl -s https://api.github.com/repos/google-deepmind/mujoco/releases/latest | grep browser_download_url | grep linux.x86_64.tar.gz | cut -d '"' -f 4 | sed '1p;d')
        curl -L $MUJOCO_URL_LATEST > mujoco.tar.gz && tar -xvzf mujoco.tar.gz
        sudo cp -r $(ls | grep mujoco | sed '1p;d') ~/.local/mujoco/
        sudo cp -a ~/.local/mujoco/lib/. /usr/lib/
      
    - uses: actions/checkout@master
    - uses: actions/cache@master
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
