name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Install Torch Depends
      run: |
        curl -sS https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/intel.gpg
        sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'

        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.1-1_all.deb
        sudo dpkg -i cuda-keyring_1.1-1_all.deb
        sudo apt-get update
        
        sudo apt-get -y install cuda libcudnn8 libcudnn8-dev intel-mkl
        echo "/usr/local/cuda/bin" >> $GITHUB_PATH
    
    - name: Install Torch
      run: |
        TORCH_URL=$(curl -s https://api.github.com/repos/pytorch/pytorch/releases/latest | grep tarball_url | cut -d '"' -f 4)
        curl -L $TORCH_URL > torch.tar.gz && tar -xzvf torch.tar.gz
        cd $(ls | grep pytorch-pytorch | sed '1p;d')
        pip install -r requirements.txt
        mkdir build && cd build
        cmake -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DPYTHON_EXECUTABLE:PATH=`which python3` -DCMAKE_INSTALL_PREFIX:PATH=~/torch/ ..
        
        echo "LIBTORCH=~/torch/" >> $GITHUB_ENV
        echo "LIBTORCH_INCLUDE=~/torch/include/" >> $GITHUB_ENV
        echo "LIBTORCH_LIB=~/torch/lib/" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=~/torch/lib/:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        
    - name: Install TA-Lib
      run: |
        curl -L  http://downloads.sourceforge.net/project/ta-lib/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz > ta-lib-0.4.0-src.tar.gz && tar -xzvf ta-lib-0.4.0-src.tar.gz
        cd ta-lib && ./configure --prefix=/usr
        make && sudo make install
        echo "RUSTFLAGS=-L /usr/lib/" >> $GITHUB_ENV
        
    - name: Install MuJoCo
      run: |
        MUJOCO_URL_LATEST=$(curl -s https://api.github.com/repos/google-deepmind/mujoco/releases/latest | grep browser_download_url | grep linux.x86_64.tar.gz | cut -d '"' -f 4 | sed '1p;d')
        curl -L $MUJOCO_URL_LATEST > mujoco.tar.gz && tar -xvzf mujoco.tar.gz
        sudo cp -r $(ls | grep mujoco | sed '1p;d') ~/.local/mujoco/
        
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
